// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiB2BScimV1ScimAttributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Address>? Addresses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Address> Addresses { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Email>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Email> Emails { get; set; }
#endif
        /// <summary>The enterprise_extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1EnterpriseExtension? EnterpriseExtension { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1EnterpriseExtension EnterpriseExtension { get; set; }
#endif
        /// <summary>The entitlements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Entitlement>? Entitlements { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Entitlement> Entitlements { get; set; }
#endif
        /// <summary>The external_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The groups property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Group>? Groups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Group> Groups { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ims property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1IMs>? Ims { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1IMs> Ims { get; set; }
#endif
        /// <summary>The locale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Name Name { get; set; }
#endif
        /// <summary>The nick_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NickName { get; set; }
#nullable restore
#else
        public string NickName { get; set; }
#endif
        /// <summary>The phone_numbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1PhoneNumber>? PhoneNumbers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1PhoneNumber> PhoneNumbers { get; set; }
#endif
        /// <summary>The photos property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Photo>? Photos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Photo> Photos { get; set; }
#endif
        /// <summary>The preferred_language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreferredLanguage { get; set; }
#nullable restore
#else
        public string PreferredLanguage { get; set; }
#endif
        /// <summary>The profile_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileUrl { get; set; }
#nullable restore
#else
        public string ProfileUrl { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Role>? Roles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Role> Roles { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The user_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>The user_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserType { get; set; }
#nullable restore
#else
        public string UserType { get; set; }
#endif
        /// <summary>The x509certificates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1X509Certificate>? X509certificates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1X509Certificate> X509certificates { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1ScimAttributes"/> and sets the default values.
        /// </summary>
        public ApiB2BScimV1ScimAttributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1ScimAttributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1ScimAttributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1ScimAttributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Address>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Address.CreateFromDiscriminatorValue)?.AsList(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Email>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Email.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enterprise_extension", n => { EnterpriseExtension = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1EnterpriseExtension>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1EnterpriseExtension.CreateFromDiscriminatorValue); } },
                { "entitlements", n => { Entitlements = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Entitlement>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Entitlement.CreateFromDiscriminatorValue)?.AsList(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "groups", n => { Groups = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Group>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Group.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "ims", n => { Ims = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1IMs>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1IMs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Name>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Name.CreateFromDiscriminatorValue); } },
                { "nick_name", n => { NickName = n.GetStringValue(); } },
                { "phone_numbers", n => { PhoneNumbers = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1PhoneNumber>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1PhoneNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "photos", n => { Photos = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Photo>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Photo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "preferred_language", n => { PreferredLanguage = n.GetStringValue(); } },
                { "profile_url", n => { ProfileUrl = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Role>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Role.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "user_name", n => { UserName = n.GetStringValue(); } },
                { "user_type", n => { UserType = n.GetStringValue(); } },
                { "x509certificates", n => { X509certificates = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1X509Certificate>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1X509Certificate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Address>("addresses", Addresses);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Email>("emails", Emails);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1EnterpriseExtension>("enterprise_extension", EnterpriseExtension);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Entitlement>("entitlements", Entitlements);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Group>("groups", Groups);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1IMs>("ims", Ims);
            writer.WriteStringValue("locale", Locale);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Name>("name", Name);
            writer.WriteStringValue("nick_name", NickName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1PhoneNumber>("phone_numbers", PhoneNumbers);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Photo>("photos", Photos);
            writer.WriteStringValue("preferred_language", PreferredLanguage);
            writer.WriteStringValue("profile_url", ProfileUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1Role>("roles", Roles);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("user_name", UserName);
            writer.WriteStringValue("user_type", UserType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BScimV1X509Certificate>("x509certificates", X509certificates);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
