// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    /// <summary>
    /// Request type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL that the end user clicks from the discovery Magic Link. This URL should be an endpoint in the backend server that  verifies the request by querying Stytch&apos;s discovery authenticate endpoint and continues the flow. If this value is not passed, the default  discovery redirect URL that you set in your Dashboard is used. If you have not set a default discovery redirect URL, an error is returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscoveryRedirectUrl { get; set; }
#nullable restore
#else
        public string DiscoveryRedirectUrl { get; set; }
#endif
        /// <summary>The email address of the Member to start the email reset process for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailAddress { get; set; }
#nullable restore
#else
        public string EmailAddress { get; set; }
#endif
        /// <summary>Used to determine which language to use when sending the user this delivery method. Parameter is an [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `&quot;en&quot;`.If no value is provided, the copy defaults to English.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The pkce_code_challenge property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PkceCodeChallenge { get; set; }
#nullable restore
#else
        public string PkceCodeChallenge { get; set; }
#endif
        /// <summary>Sets a time limit after which the email link to reset the member&apos;s password will no longer be valid. The minimum allowed expiration is 5 minutes and the maximum is 10080 minutes (7 days). By default, the expiration is 30 minutes.</summary>
        public int? ResetPasswordExpirationMinutes { get; set; }
        /// <summary>The URL that the Member is redirected to from the reset password magic link. This URL should display your application&apos;s reset password page.  Before rendering the reset page, extract the `token` from the query parameters. On the reset page, collect the new password and complete the flow by calling the corresponding Password Reset by Email endpoint.  If this parameter is not specified, the default Reset Password redirect URL configured in the Dashboard will be used. If you have not set a default Reset Password redirect URL, an error is returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetPasswordRedirectUrl { get; set; }
#nullable restore
#else
        public string ResetPasswordRedirectUrl { get; set; }
#endif
        /// <summary>Use a custom template for reset password emails. By default, it will use your default email template. Templates can be added in the [Stytch dashboard](https://stytch.com/dashboard/templates) using our built-in customization options or custom HTML templates with type “Passwords - Reset Password”.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetPasswordTemplateId { get; set; }
#nullable restore
#else
        public string ResetPasswordTemplateId { get; set; }
#endif
        /// <summary>Use a custom template for verification emails sent during password reset flows. When cross-organization passwords are enabled for your Project, this template will be used the first time a user sets a password via a  password reset flow. By default, it will use your default email template. Templates can be added in the [Stytch dashboard](https://stytch.com/dashboard/templates) using our built-in customization options or custom HTML templates with type “Passwords - Email Verification”.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifyEmailTemplateId { get; set; }
#nullable restore
#else
        public string VerifyEmailTemplateId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest"/> and sets the default values.
        /// </summary>
        public ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiB2BPasswordV1B2BPasswordsDiscoveryEmailResetStartRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "discovery_redirect_url", n => { DiscoveryRedirectUrl = n.GetStringValue(); } },
                { "email_address", n => { EmailAddress = n.GetStringValue(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "pkce_code_challenge", n => { PkceCodeChallenge = n.GetStringValue(); } },
                { "reset_password_expiration_minutes", n => { ResetPasswordExpirationMinutes = n.GetIntValue(); } },
                { "reset_password_redirect_url", n => { ResetPasswordRedirectUrl = n.GetStringValue(); } },
                { "reset_password_template_id", n => { ResetPasswordTemplateId = n.GetStringValue(); } },
                { "verify_email_template_id", n => { VerifyEmailTemplateId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("discovery_redirect_url", DiscoveryRedirectUrl);
            writer.WriteStringValue("email_address", EmailAddress);
            writer.WriteStringValue("locale", Locale);
            writer.WriteStringValue("pkce_code_challenge", PkceCodeChallenge);
            writer.WriteIntValue("reset_password_expiration_minutes", ResetPasswordExpirationMinutes);
            writer.WriteStringValue("reset_password_redirect_url", ResetPasswordRedirectUrl);
            writer.WriteStringValue("reset_password_template_id", ResetPasswordTemplateId);
            writer.WriteStringValue("verify_email_template_id", VerifyEmailTemplateId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
