// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    /// <summary>
    /// Request type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiB2bTotpV1AuthenticateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The code to authenticate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The Intermediate Session Token. This token does not necessarily belong to a specific instance of a Member, but represents a bag of factors that may be converted to a member session. The token can be used with the [OTP SMS Authenticate endpoint](https://stytch.com/docs/b2b/api/authenticate-otp-sms), [TOTP Authenticate endpoint](https://stytch.com/docs/b2b/api/authenticate-totp), or [Recovery Codes Recover endpoint](https://stytch.com/docs/b2b/api/recovery-codes-recover) to complete an MFA flow and log in to the Organization. The token has a default expiry of 10 minutes. It can also be used with the [Exchange Intermediate Session endpoint](https://stytch.com/docs/b2b/api/exchange-intermediate-session) to join a specific Organization that allows the factors represented by the intermediate session token; or the [Create Organization via Discovery endpoint](https://stytch.com/docs/b2b/api/create-organization-via-discovery) to create a new Organization and Member. Intermediate Session Tokens have a default expiry of 10 minutes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntermediateSessionToken { get; set; }
#nullable restore
#else
        public string IntermediateSessionToken { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Member. The `member_id` is critical to perform operations on a Member, so be sure to preserve this value. You may use an external_id here if one is set for the member.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations on an Organization, so be sure to preserve this value. You may also use the organization_slug or organization_external_id here as a convenience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>Add a custom claims map to the Session being authenticated. Claims are only created if a Session is initialized by providing a value in  `session_duration_minutes`. Claims will be included on the Session object and in the JWT. To update a key in an existing Session, supply a new value. To  delete a key, supply a null value. Custom claims made with reserved claims (`iss`, `sub`, `aud`, `exp`, `nbf`, `iat`, `jti`) will be ignored.  Total custom claims size cannot exceed four kilobytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest_session_custom_claims? SessionCustomClaims { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest_session_custom_claims SessionCustomClaims { get; set; }
#endif
        /// <summary>Set the session lifetime to be this many minutes from now. This will start a new session if one doesn&apos;t already exist,  returning both an opaque `session_token` and `session_jwt` for this session. Remember that the `session_jwt` will have a fixed lifetime of  five minutes regardless of the underlying session duration, and will need to be refreshed over time.  This value must be a minimum of 5 and a maximum of 527040 minutes (366 days).  If a `session_token` or `session_jwt` is provided then a successful authentication will continue to extend the session this many minutes.  If the `session_duration_minutes` parameter is not specified, a Stytch session will be created with a 60 minute duration. If you don&apos;t want  to use the Stytch session product, you can ignore the session fields in the response.</summary>
        public int? SessionDurationMinutes { get; set; }
        /// <summary>The JSON Web Token (JWT) for a given Stytch Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionJwt { get; set; }
#nullable restore
#else
        public string SessionJwt { get; set; }
#endif
        /// <summary>A secret token for a given Stytch Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionToken { get; set; }
#nullable restore
#else
        public string SessionToken { get; set; }
#endif
        /// <summary>If passed will set the authenticated method to the default MFA method. Completing an MFA authentication flow for the first time for a Member will implicitly set the method to the default MFA method. This option can be used to update the default MFA method if multiple are being used.</summary>
        public bool? SetDefaultMfa { get; set; }
        /// <summary>Optionally sets the Member’s MFA enrollment status upon a successful authentication. If the Organization’s MFA policy is `REQUIRED_FOR_ALL`, this field will be ignored. If this field is not passed in, the Member’s `mfa_enrolled` boolean will not be affected. The options are:   `enroll` – sets the Member&apos;s `mfa_enrolled` boolean to `true`. The Member will be required to complete an MFA step upon subsequent logins to the Organization.   `unenroll` –  sets the Member&apos;s `mfa_enrolled` boolean to `false`. The Member will no longer be required to complete MFA steps when logging in to the Organization.  </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SetMfaEnrollment { get; set; }
#nullable restore
#else
        public string SetMfaEnrollment { get; set; }
#endif
        /// <summary>If the `telemetry_id` is passed, as part of this request, Stytch will call the [Fingerprint Lookup API](https://stytch.com/docs/fraud/api/fingerprint-lookup) and store the associated fingerprints and IPGEO information for the Member. Your workspace must be enabled for Device Fingerprinting to use this feature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TelemetryId { get; set; }
#nullable restore
#else
        public string TelemetryId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest"/> and sets the default values.
        /// </summary>
        public ApiB2bTotpV1AuthenticateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "intermediate_session_token", n => { IntermediateSessionToken = n.GetStringValue(); } },
                { "member_id", n => { MemberId = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "session_custom_claims", n => { SessionCustomClaims = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest_session_custom_claims>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest_session_custom_claims.CreateFromDiscriminatorValue); } },
                { "session_duration_minutes", n => { SessionDurationMinutes = n.GetIntValue(); } },
                { "session_jwt", n => { SessionJwt = n.GetStringValue(); } },
                { "session_token", n => { SessionToken = n.GetStringValue(); } },
                { "set_default_mfa", n => { SetDefaultMfa = n.GetBoolValue(); } },
                { "set_mfa_enrollment", n => { SetMfaEnrollment = n.GetStringValue(); } },
                { "telemetry_id", n => { TelemetryId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("intermediate_session_token", IntermediateSessionToken);
            writer.WriteStringValue("member_id", MemberId);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bTotpV1AuthenticateRequest_session_custom_claims>("session_custom_claims", SessionCustomClaims);
            writer.WriteIntValue("session_duration_minutes", SessionDurationMinutes);
            writer.WriteStringValue("session_jwt", SessionJwt);
            writer.WriteStringValue("session_token", SessionToken);
            writer.WriteBoolValue("set_default_mfa", SetDefaultMfa);
            writer.WriteStringValue("set_mfa_enrollment", SetMfaEnrollment);
            writer.WriteStringValue("telemetry_id", TelemetryId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
