// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiB2bSessionV1MemberSession : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of different authentication factors that comprise a Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSessionV1AuthenticationFactor>? AuthenticationFactors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSessionV1AuthenticationFactor> AuthenticationFactors { get; set; }
#endif
        /// <summary>The custom claims map for a Session. Claims can be added to a session during a Sessions authenticate call.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession_custom_claims? CustomClaims { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession_custom_claims CustomClaims { get; set; }
#endif
        /// <summary>The timestamp when the Session expires. Values conform to the RFC 3339 standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiresAt { get; set; }
#nullable restore
#else
        public string ExpiresAt { get; set; }
#endif
        /// <summary>The timestamp when the Session was last accessed. Values conform to the RFC 3339 standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastAccessedAt { get; set; }
#nullable restore
#else
        public string LastAccessedAt { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Member.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberSessionId { get; set; }
#nullable restore
#else
        public string MemberSessionId { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations on an Organization, so be sure to preserve this value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>&quot;The unique URL slug of the Organization. The slug only accepts alphanumeric characters and the following reserved characters: `-` `.` `_` `~`. Must be between 2 and 128 characters in length. Wherever an organization_id is expected in a path or request parameter, you may also use the organization_slug as a convenience.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationSlug { get; set; }
#nullable restore
#else
        public string OrganizationSlug { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Roles { get; set; }
#nullable restore
#else
        public List<string> Roles { get; set; }
#endif
        /// <summary>The timestamp when the Session was created. Values conform to the RFC 3339 standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession"/> and sets the default values.
        /// </summary>
        public ApiB2bSessionV1MemberSession()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authentication_factors", n => { AuthenticationFactors = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSessionV1AuthenticationFactor>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSessionV1AuthenticationFactor.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_claims", n => { CustomClaims = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession_custom_claims>(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession_custom_claims.CreateFromDiscriminatorValue); } },
                { "expires_at", n => { ExpiresAt = n.GetStringValue(); } },
                { "last_accessed_at", n => { LastAccessedAt = n.GetStringValue(); } },
                { "member_id", n => { MemberId = n.GetStringValue(); } },
                { "member_session_id", n => { MemberSessionId = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "organization_slug", n => { OrganizationSlug = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSessionV1AuthenticationFactor>("authentication_factors", AuthenticationFactors);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1MemberSession_custom_claims>("custom_claims", CustomClaims);
            writer.WriteStringValue("expires_at", ExpiresAt);
            writer.WriteStringValue("last_accessed_at", LastAccessedAt);
            writer.WriteStringValue("member_id", MemberId);
            writer.WriteStringValue("member_session_id", MemberSessionId);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteStringValue("organization_slug", OrganizationSlug);
            writer.WriteCollectionOfPrimitiveValues<string>("roles", Roles);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
