// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiConnectedappsV1ConnectedAppWithNextClientSecret : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access_token_custom_audience property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessTokenCustomAudience { get; set; }
#nullable restore
#else
        public string AccessTokenCustomAudience { get; set; }
#endif
        /// <summary>The access_token_expiry_minutes property</summary>
        public int? AccessTokenExpiryMinutes { get; set; }
        /// <summary>The access_token_template_content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessTokenTemplateContent { get; set; }
#nullable restore
#else
        public string AccessTokenTemplateContent { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Valid for first party clients only. If true, the client does not need to request explicit user consent for the `offline_access` scope.</summary>
        public bool? BypassConsentForOfflineAccess { get; set; }
        /// <summary>A human-readable description for the client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientDescription { get; set; }
#nullable restore
#else
        public string ClientDescription { get; set; }
#endif
        /// <summary>The ID of the Connected App client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The client_id_metadata_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientIdMetadataUrl { get; set; }
#nullable restore
#else
        public string ClientIdMetadataUrl { get; set; }
#endif
        /// <summary>A human-readable name for the client.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientName { get; set; }
#nullable restore
#else
        public string ClientName { get; set; }
#endif
        /// <summary>The last four characters of the client secret.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientSecretLastFour { get; set; }
#nullable restore
#else
        public string ClientSecretLastFour { get; set; }
#endif
        /// <summary>The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and `third_party_public`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientType { get; set; }
#nullable restore
#else
        public string ClientType { get; set; }
#endif
        /// <summary>Valid for first party clients only. If `true`, an authorization token granted to this Client can be exchanged for a full Stytch session.</summary>
        public bool? FullAccessAllowed { get; set; }
        /// <summary>The logo URL of the Connected App, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogoUrl { get; set; }
#nullable restore
#else
        public string LogoUrl { get; set; }
#endif
        /// <summary>The next_client_secret property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextClientSecret { get; set; }
#nullable restore
#else
        public string NextClientSecret { get; set; }
#endif
        /// <summary>The last four characters of the `next_client_secret`. Null if no `next_client_secret` exists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextClientSecretLastFour { get; set; }
#nullable restore
#else
        public string NextClientSecretLastFour { get; set; }
#endif
        /// <summary>Array of redirect URI values for use in OIDC Logout flows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PostLogoutRedirectUrls { get; set; }
#nullable restore
#else
        public List<string> PostLogoutRedirectUrls { get; set; }
#endif
        /// <summary>Array of redirect URI values for use in OAuth Authorization flows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RedirectUrls { get; set; }
#nullable restore
#else
        public List<string> RedirectUrls { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiConnectedappsV1ConnectedAppWithNextClientSecret"/> and sets the default values.
        /// </summary>
        public ApiConnectedappsV1ConnectedAppWithNextClientSecret()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiConnectedappsV1ConnectedAppWithNextClientSecret"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiConnectedappsV1ConnectedAppWithNextClientSecret CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiConnectedappsV1ConnectedAppWithNextClientSecret();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_token_custom_audience", n => { AccessTokenCustomAudience = n.GetStringValue(); } },
                { "access_token_expiry_minutes", n => { AccessTokenExpiryMinutes = n.GetIntValue(); } },
                { "access_token_template_content", n => { AccessTokenTemplateContent = n.GetStringValue(); } },
                { "bypass_consent_for_offline_access", n => { BypassConsentForOfflineAccess = n.GetBoolValue(); } },
                { "client_description", n => { ClientDescription = n.GetStringValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_id_metadata_url", n => { ClientIdMetadataUrl = n.GetStringValue(); } },
                { "client_name", n => { ClientName = n.GetStringValue(); } },
                { "client_secret_last_four", n => { ClientSecretLastFour = n.GetStringValue(); } },
                { "client_type", n => { ClientType = n.GetStringValue(); } },
                { "full_access_allowed", n => { FullAccessAllowed = n.GetBoolValue(); } },
                { "logo_url", n => { LogoUrl = n.GetStringValue(); } },
                { "next_client_secret", n => { NextClientSecret = n.GetStringValue(); } },
                { "next_client_secret_last_four", n => { NextClientSecretLastFour = n.GetStringValue(); } },
                { "post_logout_redirect_urls", n => { PostLogoutRedirectUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "redirect_urls", n => { RedirectUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_token_custom_audience", AccessTokenCustomAudience);
            writer.WriteIntValue("access_token_expiry_minutes", AccessTokenExpiryMinutes);
            writer.WriteStringValue("access_token_template_content", AccessTokenTemplateContent);
            writer.WriteBoolValue("bypass_consent_for_offline_access", BypassConsentForOfflineAccess);
            writer.WriteStringValue("client_description", ClientDescription);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_id_metadata_url", ClientIdMetadataUrl);
            writer.WriteStringValue("client_name", ClientName);
            writer.WriteStringValue("client_secret_last_four", ClientSecretLastFour);
            writer.WriteStringValue("client_type", ClientType);
            writer.WriteBoolValue("full_access_allowed", FullAccessAllowed);
            writer.WriteStringValue("logo_url", LogoUrl);
            writer.WriteStringValue("next_client_secret", NextClientSecret);
            writer.WriteStringValue("next_client_secret_last_four", NextClientSecretLastFour);
            writer.WriteCollectionOfPrimitiveValues<string>("post_logout_redirect_urls", PostLogoutRedirectUrls);
            writer.WriteCollectionOfPrimitiveValues<string>("redirect_urls", RedirectUrls);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
