// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiConnectedappsV1CreateRequestClientType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "first_party")]
        #pragma warning disable CS1591
        First_party,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_party_public")]
        #pragma warning disable CS1591
        First_party_public,
        #pragma warning restore CS1591
        [EnumMember(Value = "third_party")]
        #pragma warning disable CS1591
        Third_party,
        #pragma warning restore CS1591
        [EnumMember(Value = "third_party_public")]
        #pragma warning disable CS1591
        Third_party_public,
        #pragma warning restore CS1591
    }
}
