// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    /// <summary>
    /// Request type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiCryptoWalletV1AuthenticateStartRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The crypto wallet address to authenticate.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoWalletAddress { get; set; }
#nullable restore
#else
        public string CryptoWalletAddress { get; set; }
#endif
        /// <summary>The type of wallet to authenticate. Currently `ethereum` and `solana` are supported. Wallets for any EVM-compatible chains (such as Polygon or BSC) are also supported and are grouped under the `ethereum` type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CryptoWalletType { get; set; }
#nullable restore
#else
        public string CryptoWalletType { get; set; }
#endif
        /// <summary>The `session_jwt` associated with a User&apos;s existing Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionJwt { get; set; }
#nullable restore
#else
        public string SessionJwt { get; set; }
#endif
        /// <summary>The `session_token` associated with a User&apos;s existing Session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionToken { get; set; }
#nullable restore
#else
        public string SessionToken { get; set; }
#endif
        /// <summary>The siwe_params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1SiweParams? SiweParams { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1SiweParams SiweParams { get; set; }
#endif
        /// <summary>The unique ID of a specific User. You may use an `external_id` here if one is set for the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1AuthenticateStartRequest"/> and sets the default values.
        /// </summary>
        public ApiCryptoWalletV1AuthenticateStartRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1AuthenticateStartRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1AuthenticateStartRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1AuthenticateStartRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "crypto_wallet_address", n => { CryptoWalletAddress = n.GetStringValue(); } },
                { "crypto_wallet_type", n => { CryptoWalletType = n.GetStringValue(); } },
                { "session_jwt", n => { SessionJwt = n.GetStringValue(); } },
                { "session_token", n => { SessionToken = n.GetStringValue(); } },
                { "siwe_params", n => { SiweParams = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1SiweParams>(global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1SiweParams.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("crypto_wallet_address", CryptoWalletAddress);
            writer.WriteStringValue("crypto_wallet_type", CryptoWalletType);
            writer.WriteStringValue("session_jwt", SessionJwt);
            writer.WriteStringValue("session_token", SessionToken);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiCryptoWalletV1SiweParams>("siwe_params", SiweParams);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
