// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiDiscoveryV1ExchangeRequestLocale
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "en")]
        #pragma warning disable CS1591
        En,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt-br")]
        #pragma warning disable CS1591
        PtBr,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "de-DE")]
        #pragma warning disable CS1591
        DeDe,
        #pragma warning restore CS1591
        [EnumMember(Value = "zh-Hans")]
        #pragma warning disable CS1591
        ZhHans,
        #pragma warning restore CS1591
        [EnumMember(Value = "ca-ES")]
        #pragma warning disable CS1591
        CaEs,
        #pragma warning restore CS1591
    }
}
