// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiFraudV1RuleType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "VISITOR_ID")]
        #pragma warning disable CS1591
        VisitorId,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROWSER_ID")]
        #pragma warning disable CS1591
        BrowserId,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISITOR_FINGERPRINT")]
        #pragma warning disable CS1591
        VisitorFingerprint,
        #pragma warning restore CS1591
        [EnumMember(Value = "BROWSER_FINGERPRINT")]
        #pragma warning disable CS1591
        BrowserFingerprint,
        #pragma warning restore CS1591
        [EnumMember(Value = "HARDWARE_FINGERPRINT")]
        #pragma warning disable CS1591
        HardwareFingerprint,
        #pragma warning restore CS1591
        [EnumMember(Value = "NETWORK_FINGERPRINT")]
        #pragma warning disable CS1591
        NetworkFingerprint,
        #pragma warning restore CS1591
        [EnumMember(Value = "CIDR_BLOCK")]
        #pragma warning disable CS1591
        CidrBlock,
        #pragma warning restore CS1591
        [EnumMember(Value = "ASN")]
        #pragma warning disable CS1591
        Asn,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTRY_CODE")]
        #pragma warning disable CS1591
        CountryCode,
        #pragma warning restore CS1591
    }
}
