// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiFraudV1VerdictReasonAction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The default_action property</summary>
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction? DefaultAction { get; set; }
        /// <summary>The override_action property</summary>
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction? OverrideAction { get; set; }
        /// <summary>The time when the override was created, if one exists. Values conform to the RFC 3339 standard and are expressed in UTC, e.g. `2021-12-29T12:33:09Z`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OverrideCreatedAt { get; set; }
#nullable restore
#else
        public string OverrideCreatedAt { get; set; }
#endif
        /// <summary>A description of the override, if one exists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OverrideDescription { get; set; }
#nullable restore
#else
        public string OverrideDescription { get; set; }
#endif
        /// <summary>The verdict reason.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerdictReason { get; set; }
#nullable restore
#else
        public string VerdictReason { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonAction"/> and sets the default values.
        /// </summary>
        public ApiFraudV1VerdictReasonAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_action", n => { DefaultAction = n.GetEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction>(); } },
                { "override_action", n => { OverrideAction = n.GetEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction>(); } },
                { "override_created_at", n => { OverrideCreatedAt = n.GetStringValue(); } },
                { "override_description", n => { OverrideDescription = n.GetStringValue(); } },
                { "verdict_reason", n => { VerdictReason = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction>("default_action", DefaultAction);
            writer.WriteEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1VerdictReasonActionAction>("override_action", OverrideAction);
            writer.WriteStringValue("override_created_at", OverrideCreatedAt);
            writer.WriteStringValue("override_description", OverrideDescription);
            writer.WriteStringValue("verdict_reason", VerdictReason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
