// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiFraudV1Fingerprints : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Combination of signals to identify a browser and its specific version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrowserFingerprint { get; set; }
#nullable restore
#else
        public string BrowserFingerprint { get; set; }
#endif
        /// <summary>Combination of VisitorID and NetworkFingerprint to create a clear identifier of a browser.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrowserId { get; set; }
#nullable restore
#else
        public string BrowserId { get; set; }
#endif
        /// <summary>Combinations of signals to identify an operating system and architecture.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HardwareFingerprint { get; set; }
#nullable restore
#else
        public string HardwareFingerprint { get; set; }
#endif
        /// <summary>Combination of signals associated with a specific network commonly known as TLS fingerprinting. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkFingerprint { get; set; }
#nullable restore
#else
        public string NetworkFingerprint { get; set; }
#endif
        /// <summary>Cookie-less way of identifying a unique user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VisitorFingerprint { get; set; }
#nullable restore
#else
        public string VisitorFingerprint { get; set; }
#endif
        /// <summary>The cookie stored on the user&apos;s device that uniquely identifies them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VisitorId { get; set; }
#nullable restore
#else
        public string VisitorId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1Fingerprints"/> and sets the default values.
        /// </summary>
        public ApiFraudV1Fingerprints()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1Fingerprints"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1Fingerprints CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiFraudV1Fingerprints();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "browser_fingerprint", n => { BrowserFingerprint = n.GetStringValue(); } },
                { "browser_id", n => { BrowserId = n.GetStringValue(); } },
                { "hardware_fingerprint", n => { HardwareFingerprint = n.GetStringValue(); } },
                { "network_fingerprint", n => { NetworkFingerprint = n.GetStringValue(); } },
                { "visitor_fingerprint", n => { VisitorFingerprint = n.GetStringValue(); } },
                { "visitor_id", n => { VisitorId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("browser_fingerprint", BrowserFingerprint);
            writer.WriteStringValue("browser_id", BrowserId);
            writer.WriteStringValue("hardware_fingerprint", HardwareFingerprint);
            writer.WriteStringValue("network_fingerprint", NetworkFingerprint);
            writer.WriteStringValue("visitor_fingerprint", VisitorFingerprint);
            writer.WriteStringValue("visitor_id", VisitorId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
