// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiFraudV1VerdictReasonActionAction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ALLOW")]
        #pragma warning disable CS1591
        ALLOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHALLENGE")]
        #pragma warning disable CS1591
        CHALLENGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BLOCK")]
        #pragma warning disable CS1591
        BLOCK,
        #pragma warning restore CS1591
    }
}
