// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiOrganizationV1OAuthRegistration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If available, the `locale` is the Member&apos;s locale set in the OAuth identity provider that the user has authenticated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The unique ID of an OAuth registration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberOauthRegistrationId { get; set; }
#nullable restore
#else
        public string MemberOauthRegistrationId { get; set; }
#endif
        /// <summary>If available, the `profile_picture_url` is a URL of the User&apos;s profile picture set in OAuth identity the provider that the User has authenticated with, e.g. Google profile picture.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfilePictureUrl { get; set; }
#nullable restore
#else
        public string ProfilePictureUrl { get; set; }
#endif
        /// <summary>The unique identifier for the User within a given OAuth provider. Also commonly called the `sub` or &quot;Subject field&quot; in OAuth protocols.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderSubject { get; set; }
#nullable restore
#else
        public string ProviderSubject { get; set; }
#endif
        /// <summary>Denotes the OAuth identity provider that the user has authenticated with, e.g. Google, Microsoft, GitHub etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderType { get; set; }
#nullable restore
#else
        public string ProviderType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OAuthRegistration"/> and sets the default values.
        /// </summary>
        public ApiOrganizationV1OAuthRegistration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OAuthRegistration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OAuthRegistration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OAuthRegistration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "member_oauth_registration_id", n => { MemberOauthRegistrationId = n.GetStringValue(); } },
                { "profile_picture_url", n => { ProfilePictureUrl = n.GetStringValue(); } },
                { "provider_subject", n => { ProviderSubject = n.GetStringValue(); } },
                { "provider_type", n => { ProviderType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("locale", Locale);
            writer.WriteStringValue("member_oauth_registration_id", MemberOauthRegistrationId);
            writer.WriteStringValue("profile_picture_url", ProfilePictureUrl);
            writer.WriteStringValue("provider_subject", ProviderSubject);
            writer.WriteStringValue("provider_type", ProviderType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
