// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApiOrganizationV1OrganizationsMembersStartEmailUpdateRequestDeliveryMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "EMAIL_MAGIC_LINK")]
        #pragma warning disable CS1591
        EmailMagicLink,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL_OTP")]
        #pragma warning disable CS1591
        EmailOtp,
        #pragma warning restore CS1591
    }
}
