// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    /// <summary>
    /// Request type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiPasswordV1PasswordsEmailResetStartRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiAttributeV1Attributes? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiAttributeV1Attributes Attributes { get; set; }
#endif
        /// <summary>A base64url encoded SHA256 hash of a one time secret used to validate that the request starts and ends on the same device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeChallenge { get; set; }
#nullable restore
#else
        public string CodeChallenge { get; set; }
#endif
        /// <summary>The email of the User that requested the password reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The locale property</summary>
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1ResetStartRequestLocale? Locale { get; set; }
        /// <summary>The URL that Users are redirected to upon clicking the &quot;Log in without password&quot; button in password reset emails.      After Users are redirected to the login redirect URL, your application should retrieve the `token` value from the URL parameters and call the [Magic Link Authenticate endpoint](https://stytch.com/docs/api/authenticate-magic-link) to log the User in without requiring a password reset. If this value is not provided, your project&apos;s default login redirect URL will be used. If you have not set a default login redirect URL, an error will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoginRedirectUrl { get; set; }
#nullable restore
#else
        public string LoginRedirectUrl { get; set; }
#endif
        /// <summary>Set the expiration for the password reset, in minutes. By default, it expires in 30 minutes.  The minimum expiration is 5 minutes and the maximum is 7 days (10080 mins).</summary>
        public int? ResetPasswordExpirationMinutes { get; set; }
        /// <summary>The URL that the User is redirected to from the reset password magic link. This URL should display your application&apos;s reset password page.  Before rendering the reset page, extract the `token` from the query parameters. On the reset page, collect the new password and complete the flow by calling the corresponding Password Reset by Email endpoint.  If this parameter is not specified, the default Reset Password redirect URL configured in the Dashboard will be used. If you have not set a default Reset Password redirect URL, an error is returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetPasswordRedirectUrl { get; set; }
#nullable restore
#else
        public string ResetPasswordRedirectUrl { get; set; }
#endif
        /// <summary>Use a custom template for password reset emails. By default, it will use your default email template.  Templates can be added in the [Stytch dashboard](https://stytch.com/dashboard/templates) using our built-in customization options or custom HTML templates with type “Passwords - Password reset”.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetPasswordTemplateId { get; set; }
#nullable restore
#else
        public string ResetPasswordTemplateId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1PasswordsEmailResetStartRequest"/> and sets the default values.
        /// </summary>
        public ApiPasswordV1PasswordsEmailResetStartRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1PasswordsEmailResetStartRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1PasswordsEmailResetStartRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1PasswordsEmailResetStartRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiAttributeV1Attributes>(global::Soenneker.Stytch.OpenApiClient.Models.ApiAttributeV1Attributes.CreateFromDiscriminatorValue); } },
                { "code_challenge", n => { CodeChallenge = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "locale", n => { Locale = n.GetEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1ResetStartRequestLocale>(); } },
                { "login_redirect_url", n => { LoginRedirectUrl = n.GetStringValue(); } },
                { "reset_password_expiration_minutes", n => { ResetPasswordExpirationMinutes = n.GetIntValue(); } },
                { "reset_password_redirect_url", n => { ResetPasswordRedirectUrl = n.GetStringValue(); } },
                { "reset_password_template_id", n => { ResetPasswordTemplateId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiAttributeV1Attributes>("attributes", Attributes);
            writer.WriteStringValue("code_challenge", CodeChallenge);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1ResetStartRequestLocale>("locale", Locale);
            writer.WriteStringValue("login_redirect_url", LoginRedirectUrl);
            writer.WriteIntValue("reset_password_expiration_minutes", ResetPasswordExpirationMinutes);
            writer.WriteStringValue("reset_password_redirect_url", ResetPasswordRedirectUrl);
            writer.WriteStringValue("reset_password_template_id", ResetPasswordTemplateId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
