// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    /// <summary>
    /// Request type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiSsoV1SsoOidcUpdateConnectionRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object that represents the attributes used to identify a Member. This object will map the IdP-defined User attributes to Stytch-specific values, which will appear on the member&apos;s Trusted Metadata.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest_attribute_mapping? AttributeMapping { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest_attribute_mapping AttributeMapping { get; set; }
#endif
        /// <summary>The location of the URL that starts an OAuth login at the IdP. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthorizationUrl { get; set; }
#nullable restore
#else
        public string AuthorizationUrl { get; set; }
#endif
        /// <summary>The OAuth2.0 client ID used to authenticate login attempts. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The secret belonging to the OAuth2.0 client used to authenticate login attempts. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientSecret { get; set; }
#nullable restore
#else
        public string ClientSecret { get; set; }
#endif
        /// <summary>Include a space-separated list of custom scopes that you&apos;d like to include. Note that this list must be URL encoded, e.g. the spaces must be expressed as %20.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomScopes { get; set; }
#nullable restore
#else
        public string CustomScopes { get; set; }
#endif
        /// <summary>A human-readable display name for the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The identity_provider property</summary>
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1UpdateConnectionRequestIdentityProvider? IdentityProvider { get; set; }
        /// <summary>A case-sensitive `https://` URL that uniquely identifies the IdP. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Issuer { get; set; }
#nullable restore
#else
        public string Issuer { get; set; }
#endif
        /// <summary>The location of the IdP&apos;s JSON Web Key Set, used to verify credentials issued by the IdP. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JwksUrl { get; set; }
#nullable restore
#else
        public string JwksUrl { get; set; }
#endif
        /// <summary>The location of the URL that issues OAuth2.0 access tokens and OIDC ID tokens. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenUrl { get; set; }
#nullable restore
#else
        public string TokenUrl { get; set; }
#endif
        /// <summary>The location of the IDP&apos;s [UserInfo Endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo). This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserinfoUrl { get; set; }
#nullable restore
#else
        public string UserinfoUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest"/> and sets the default values.
        /// </summary>
        public ApiSsoV1SsoOidcUpdateConnectionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attribute_mapping", n => { AttributeMapping = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest_attribute_mapping>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest_attribute_mapping.CreateFromDiscriminatorValue); } },
                { "authorization_url", n => { AuthorizationUrl = n.GetStringValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "client_secret", n => { ClientSecret = n.GetStringValue(); } },
                { "custom_scopes", n => { CustomScopes = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "identity_provider", n => { IdentityProvider = n.GetEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1UpdateConnectionRequestIdentityProvider>(); } },
                { "issuer", n => { Issuer = n.GetStringValue(); } },
                { "jwks_url", n => { JwksUrl = n.GetStringValue(); } },
                { "token_url", n => { TokenUrl = n.GetStringValue(); } },
                { "userinfo_url", n => { UserinfoUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SsoOidcUpdateConnectionRequest_attribute_mapping>("attribute_mapping", AttributeMapping);
            writer.WriteStringValue("authorization_url", AuthorizationUrl);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("client_secret", ClientSecret);
            writer.WriteStringValue("custom_scopes", CustomScopes);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteEnumValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1UpdateConnectionRequestIdentityProvider>("identity_provider", IdentityProvider);
            writer.WriteStringValue("issuer", Issuer);
            writer.WriteStringValue("jwks_url", JwksUrl);
            writer.WriteStringValue("token_url", TokenUrl);
            writer.WriteStringValue("userinfo_url", UserinfoUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
