// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Stytch.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiSsoV1SamlConnection : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The URL of the Assertion Consumer Service. This value will be passed to the IdP to redirect the Member back to Stytch after a sign-in attempt. Read our [SAML Overview](https://stytch.com/docs/b2b/api/saml-overview) for more info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcsUrl { get; set; }
#nullable restore
#else
        public string AcsUrl { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allow_gateway_callback property</summary>
        public bool? AllowGatewayCallback { get; set; }
        /// <summary>An alternative URL to use for the `AssertionConsumerServiceURL` in SP initiated SAML AuthNRequests. This value can be used when you wish to migrate an existing SAML integration to Stytch with zero downtime. Note that you will be responsible for proxying requests sent to the Alternative ACS URL to Stytch. Read our [SSO migration guide](https://stytch.com/docs/b2b/guides/migrations/additional-migration-considerations) for more info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternativeAcsUrl { get; set; }
#nullable restore
#else
        public string AlternativeAcsUrl { get; set; }
#endif
        /// <summary>An alternative URL to use for the Audience Restriction. This value can be used when you wish to migrate an existing SAML integration to Stytch with zero downtime. Read our [SSO migration guide](https://stytch.com/docs/b2b/guides/migrations/additional-migration-considerations) for more info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternativeAudienceUri { get; set; }
#nullable restore
#else
        public string AlternativeAudienceUri { get; set; }
#endif
        /// <summary>&quot;An object that represents the attributes used to identify a Member. This object will map the IdP-defined User attributes to Stytch-specific values. Required attributes: `email` and one of `full_name` or `first_name` and `last_name`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionAttributeMappingProperty? AttributeMapping { get; set; }
#nullable restore
#else
        public global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionAttributeMappingProperty AttributeMapping { get; set; }
#endif
        /// <summary>The URL of the Audience Restriction. This value will indicate that Stytch is the intended audience of an assertion. Read our [SAML Overview](https://stytch.com/docs/b2b/api/saml-overview) for more info.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudienceUri { get; set; }
#nullable restore
#else
        public string AudienceUri { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific SAML Connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>A human-readable display name for the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The encryption_private_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1EncryptionPrivateKey>? EncryptionPrivateKeys { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1EncryptionPrivateKey> EncryptionPrivateKeys { get; set; }
#endif
        /// <summary>&quot;Name of the IdP. Enum with possible values: `classlink`, `cyberark`, `duo`, `google-workspace`, `jumpcloud`, `keycloak`, `miniorange`, `microsoft-entra`, `okta`, `onelogin`, `pingfederate`, `rippling`, `salesforce`, `shibboleth`, or `generic`.Specifying a known provider allows Stytch to handle any provider-specific logic.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdentityProvider { get; set; }
#nullable restore
#else
        public string IdentityProvider { get; set; }
#endif
        /// <summary>A globally unique name for the IdP. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdpEntityId { get; set; }
#nullable restore
#else
        public string IdpEntityId { get; set; }
#endif
        /// <summary>Determines whether IDP initiated auth is allowed for a given SAML connection. Defaults to false (IDP Initiated Auth is enabled).</summary>
        public bool? IdpInitiatedAuthDisabled { get; set; }
        /// <summary>The URL for which assertions for login requests will be sent. This will be provided by the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdpSsoUrl { get; set; }
#nullable restore
#else
        public string IdpSsoUrl { get; set; }
#endif
        /// <summary>The NameID format the SAML Connection expects to use. Defaults to `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NameidFormat { get; set; }
#nullable restore
#else
        public string NameidFormat { get; set; }
#endif
        /// <summary>Globally unique UUID that identifies a specific Organization. The `organization_id` is critical to perform operations on an Organization, so be sure to preserve this value. You may also use the organization_slug or organization_external_id here as a convenience.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationId { get; set; }
#nullable restore
#else
        public string OrganizationId { get; set; }
#endif
        /// <summary>All Members who log in with this SAML connection will implicitly receive the specified Roles. See the [RBAC guide](https://stytch.com/docs/b2b/guides/rbac/role-assignment) for more information about role assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionImplicitRoleAssignment>? SamlConnectionImplicitRoleAssignments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionImplicitRoleAssignment> SamlConnectionImplicitRoleAssignments { get; set; }
#endif
        /// <summary>Defines the names of the SAML groups that grant specific role assignments. For each group-Role pair, if a Member logs in with this SAML connection and belongs to the specified SAML group, they will be granted the associated Role. See the [RBAC guide](https://stytch.com/docs/b2b/guides/rbac/role-assignment) for more information about role assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlGroupImplicitRoleAssignment>? SamlGroupImplicitRoleAssignments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlGroupImplicitRoleAssignment> SamlGroupImplicitRoleAssignments { get; set; }
#endif
        /// <summary>A list of X.509 certificates Stytch will use to sign its assertion requests. Certificates should be uploaded to the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>? SigningCertificates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate> SigningCertificates { get; set; }
#endif
        /// <summary>The status of the connection. The possible values are pending or active. See the [Update SAML Connection endpoint](https://stytch.com/docs/b2b/api/update-saml-connection) for more details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>A list of X.509 certificates Stytch will use to validate an assertion callback. Certificates should be populated from the IdP.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>? VerificationCertificates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate> VerificationCertificates { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnection"/> and sets the default values.
        /// </summary>
        public ApiSsoV1SamlConnection()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acs_url", n => { AcsUrl = n.GetStringValue(); } },
                { "allow_gateway_callback", n => { AllowGatewayCallback = n.GetBoolValue(); } },
                { "alternative_acs_url", n => { AlternativeAcsUrl = n.GetStringValue(); } },
                { "alternative_audience_uri", n => { AlternativeAudienceUri = n.GetStringValue(); } },
                { "attribute_mapping", n => { AttributeMapping = n.GetObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionAttributeMappingProperty>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionAttributeMappingProperty.CreateFromDiscriminatorValue); } },
                { "audience_uri", n => { AudienceUri = n.GetStringValue(); } },
                { "connection_id", n => { ConnectionId = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "encryption_private_keys", n => { EncryptionPrivateKeys = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1EncryptionPrivateKey>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1EncryptionPrivateKey.CreateFromDiscriminatorValue)?.AsList(); } },
                { "identity_provider", n => { IdentityProvider = n.GetStringValue(); } },
                { "idp_entity_id", n => { IdpEntityId = n.GetStringValue(); } },
                { "idp_initiated_auth_disabled", n => { IdpInitiatedAuthDisabled = n.GetBoolValue(); } },
                { "idp_sso_url", n => { IdpSsoUrl = n.GetStringValue(); } },
                { "nameid_format", n => { NameidFormat = n.GetStringValue(); } },
                { "organization_id", n => { OrganizationId = n.GetStringValue(); } },
                { "saml_connection_implicit_role_assignments", n => { SamlConnectionImplicitRoleAssignments = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionImplicitRoleAssignment>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionImplicitRoleAssignment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "saml_group_implicit_role_assignments", n => { SamlGroupImplicitRoleAssignments = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlGroupImplicitRoleAssignment>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlGroupImplicitRoleAssignment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signing_certificates", n => { SigningCertificates = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "verification_certificates", n => { VerificationCertificates = n.GetCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>(global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acs_url", AcsUrl);
            writer.WriteBoolValue("allow_gateway_callback", AllowGatewayCallback);
            writer.WriteStringValue("alternative_acs_url", AlternativeAcsUrl);
            writer.WriteStringValue("alternative_audience_uri", AlternativeAudienceUri);
            writer.WriteObjectValue<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionAttributeMappingProperty>("attribute_mapping", AttributeMapping);
            writer.WriteStringValue("audience_uri", AudienceUri);
            writer.WriteStringValue("connection_id", ConnectionId);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1EncryptionPrivateKey>("encryption_private_keys", EncryptionPrivateKeys);
            writer.WriteStringValue("identity_provider", IdentityProvider);
            writer.WriteStringValue("idp_entity_id", IdpEntityId);
            writer.WriteBoolValue("idp_initiated_auth_disabled", IdpInitiatedAuthDisabled);
            writer.WriteStringValue("idp_sso_url", IdpSsoUrl);
            writer.WriteStringValue("nameid_format", NameidFormat);
            writer.WriteStringValue("organization_id", OrganizationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlConnectionImplicitRoleAssignment>("saml_connection_implicit_role_assignments", SamlConnectionImplicitRoleAssignments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1SamlGroupImplicitRoleAssignment>("saml_group_implicit_role_assignments", SamlGroupImplicitRoleAssignments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>("signing_certificates", SigningCertificates);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Stytch.OpenApiClient.Models.ApiSsoV1X509Certificate>("verification_certificates", VerificationCertificates);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
