// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Organizations;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Policy;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\rbac
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RbacRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The organizations property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The policy property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Policy.PolicyRequestBuilder Policy
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.Policy.PolicyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.RbacRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RbacRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/rbac", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Rbac.RbacRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RbacRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/rbac", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
