// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.Models;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Connected_apps;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.External_id;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oauth_providers;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oidc_providers;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Reactivate;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Start_email_update;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Totp;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Unlink_retired_email;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\organizations\{organization_id}\members\{member_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMember_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connected_apps property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Connected_apps.Connected_appsRequestBuilder Connected_apps
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Connected_apps.Connected_appsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The external_id property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.External_id.External_idRequestBuilder External_id
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.External_id.External_idRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth_providers property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oauth_providers.Oauth_providersRequestBuilder Oauth_providers
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oauth_providers.Oauth_providersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oidc_providers property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oidc_providers.Oidc_providersRequestBuilder Oidc_providers
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Oidc_providers.Oidc_providersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reactivate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Reactivate.ReactivateRequestBuilder Reactivate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Reactivate.ReactivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start_email_update property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Start_email_update.Start_email_updateRequestBuilder Start_email_update
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Start_email_update.Start_email_updateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totp property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Totp.TotpRequestBuilder Totp
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Totp.TotpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unlink_retired_email property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Unlink_retired_email.Unlink_retired_emailRequestBuilder Unlink_retired_email
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.Unlink_retired_email.Unlink_retired_emailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.WithMember_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMember_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/organizations/{organization_id}/members/{member_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.WithMember_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMember_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/organizations/{organization_id}/members/{member_id}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a Member specified by `organization_id` and `member_id`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersDeleteResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersDeleteResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersDeleteResponse>(requestInfo, global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a Member specified by `organization_id` and `member_id`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateResponse"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateResponse?> PutAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateResponse> PutAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateResponse>(requestInfo, global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a Member specified by `organization_id` and `member_id`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates a Member specified by `organization_id` and `member_id`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiOrganizationV1OrganizationsMembersUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.WithMember_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.WithMember_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Item.Members.Item.WithMember_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
