// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.Rules.List;
using Soenneker.Stytch.OpenApiClient.V1.Rules.Set;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.Rules
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\rules
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RulesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Rules.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Rules.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The set property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Rules.Set.SetRequestBuilder Set
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Rules.Set.SetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Rules.RulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RulesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/rules", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Rules.RulesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RulesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/rules", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
