// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.Models;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.Start;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\passwords\discovery\email\reset
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The start property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.Start.StartRequestBuilder Start
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.ResetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/passwords/discovery/email/reset", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.ResetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/passwords/discovery/email/reset", rawUrl)
        {
        }
        /// <summary>
        /// Reset the password associated with an email and start an intermediate session. This endpoint checks that the password reset token is valid, hasn’t expired, or already been used.The provided password needs to meet the project&apos;s password strength requirements, which can be checked in advance with the password strength endpoint. If the token and password are accepted, the password is securely stored for future authentication and the user is authenticated.Resetting a password will start an intermediate session and return a list of discovered organizations the session can be exchanged into.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetResponse"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetResponse?> PostAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetResponse> PostAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetResponse>(requestInfo, global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Reset the password associated with an email and start an intermediate session. This endpoint checks that the password reset token is valid, hasn’t expired, or already been used.The provided password needs to meet the project&apos;s password strength requirements, which can be checked in advance with the password strength endpoint. If the token and password are accepted, the password is securely stored for future authentication and the user is authenticated.Resetting a password will start an intermediate session and return a list of discovered organizations the session can be exchanged into.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bPasswordV1B2bPasswordsDiscoveryEmailResetRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.ResetRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.ResetRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Passwords.Discovery.Email.Reset.ResetRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
