// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\organizations\members\dangerously_get
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dangerously_getRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Stytch.OpenApiClient.v1.b2b.organizations.members.dangerously_get.item collection</summary>
        /// <param name="position">Globally unique UUID that identifies a specific Member. The `member_id` is critical to perform operations on a Member, so be sure to preserve this value.</param>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Item.WithMember_ItemRequestBuilder"/></returns>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Item.WithMember_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("member_id", position);
                return new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Item.WithMember_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Dangerously_getRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Dangerously_getRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/organizations/members/dangerously_get", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Organizations.Members.Dangerously_get.Dangerously_getRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Dangerously_getRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/organizations/members/dangerously_get", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
