// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.Models;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Attest;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Authenticate;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange_access_token;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Jwks;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Migrate;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Revoke;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attest property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Attest.AttestRequestBuilder Attest
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Attest.AttestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The authenticate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Authenticate.AuthenticateRequestBuilder Authenticate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Authenticate.AuthenticateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exchange property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange.ExchangeRequestBuilder Exchange
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange.ExchangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exchange_access_token property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange_access_token.Exchange_access_tokenRequestBuilder Exchange_access_token
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Exchange_access_token.Exchange_access_tokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jwks property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Jwks.JwksRequestBuilder Jwks
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Jwks.JwksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The migrate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Migrate.MigrateRequestBuilder Migrate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Migrate.MigrateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The revoke property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Revoke.RevokeRequestBuilder Revoke
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.Revoke.RevokeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/sessions?member_id={member_id}&organization_id={organization_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/sessions?member_id={member_id}&organization_id={organization_id}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves all active Sessions for a Member.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1GetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder.SessionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1GetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder.SessionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1GetResponse>(requestInfo, global::Soenneker.Stytch.OpenApiClient.Models.ApiB2bSessionV1GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves all active Sessions for a Member.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder.SessionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder.SessionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sessions.SessionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves all active Sessions for a Member.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SessionsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("member_id")]
            public string? MemberId { get; set; }
#nullable restore
#else
            [QueryParameter("member_id")]
            public string MemberId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("organization_id")]
            public string? OrganizationId { get; set; }
#nullable restore
#else
            [QueryParameter("organization_id")]
            public string OrganizationId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
