// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.Models;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Authenticate;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Email;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Existing_password;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Migrate;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Session;
using Soenneker.Stytch.OpenApiClient.V1.Passwords.Strength_check;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.Passwords
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\passwords
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PasswordsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authenticate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Authenticate.AuthenticateRequestBuilder Authenticate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Authenticate.AuthenticateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The existing_password property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Existing_password.Existing_passwordRequestBuilder Existing_password
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Existing_password.Existing_passwordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The migrate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Migrate.MigrateRequestBuilder Migrate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Migrate.MigrateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The session property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Session.SessionRequestBuilder Session
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Session.SessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The strength_check property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Strength_check.Strength_checkRequestBuilder Strength_check
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.Strength_check.Strength_checkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasswordsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/passwords", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasswordsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/passwords", rawUrl)
        {
        }
        /// <summary>
        /// Create a new user with a password. If `session_duration_minutes` is specified, a new session will be started as well.If a user with this email already exists in your Stytch project, this endpoint will return a `duplicate_email` error. To add a password to an existing passwordless user, you&apos;ll need to either call the [Migrate password endpoint](https://stytch.com/docs/api/password-migrate) or prompt the user to complete one of our password reset flows.This endpoint will return an error if the password provided does not meet our strength requirements, which you can check beforehand via the [Password strength check endpoint](https://stytch.com/docs/api/password-strength-check).When creating new Passwords users, it&apos;s good practice to enforce an email verification flow. We&apos;d recommend checking out our [Email verification guide](https://stytch.com/docs/guides/passwords/email-verification/overview) for more information.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateResponse"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateResponse?> PostAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateResponse> PostAsync(global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateResponse>(requestInfo, global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new user with a password. If `session_duration_minutes` is specified, a new session will be started as well.If a user with this email already exists in your Stytch project, this endpoint will return a `duplicate_email` error. To add a password to an existing passwordless user, you&apos;ll need to either call the [Migrate password endpoint](https://stytch.com/docs/api/password-migrate) or prompt the user to complete one of our password reset flows.This endpoint will return an error if the password provided does not meet our strength requirements, which you can check beforehand via the [Password strength check endpoint](https://stytch.com/docs/api/password-strength-check).When creating new Passwords users, it&apos;s good practice to enforce an email verification flow. We&apos;d recommend checking out our [Email verification guide](https://stytch.com/docs/guides/passwords/email-verification/overview) for more information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request type</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Stytch.OpenApiClient.Models.ApiPasswordV1CreateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
