// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Exchange;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\discovery\intermediate_sessions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Intermediate_sessionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The exchange property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Exchange.ExchangeRequestBuilder Exchange
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Exchange.ExchangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Intermediate_sessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Intermediate_sessionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/discovery/intermediate_sessions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Intermediate_sessionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Intermediate_sessionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/discovery/intermediate_sessions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
