// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b;
using Soenneker.Stytch.OpenApiClient.V1.Connected_apps;
using Soenneker.Stytch.OpenApiClient.V1.Crypto_wallets;
using Soenneker.Stytch.OpenApiClient.V1.Debug;
using Soenneker.Stytch.OpenApiClient.V1.Email;
using Soenneker.Stytch.OpenApiClient.V1.Fingerprint;
using Soenneker.Stytch.OpenApiClient.V1.Idp;
using Soenneker.Stytch.OpenApiClient.V1.Impersonation;
using Soenneker.Stytch.OpenApiClient.V1.M2m;
using Soenneker.Stytch.OpenApiClient.V1.Magic_links;
using Soenneker.Stytch.OpenApiClient.V1.Oauth;
using Soenneker.Stytch.OpenApiClient.V1.Otps;
using Soenneker.Stytch.OpenApiClient.V1.Passwords;
using Soenneker.Stytch.OpenApiClient.V1.Projects;
using Soenneker.Stytch.OpenApiClient.V1.Rbac;
using Soenneker.Stytch.OpenApiClient.V1.Rules;
using Soenneker.Stytch.OpenApiClient.V1.Sessions;
using Soenneker.Stytch.OpenApiClient.V1.Totps;
using Soenneker.Stytch.OpenApiClient.V1.Users;
using Soenneker.Stytch.OpenApiClient.V1.Verdict_reasons;
using Soenneker.Stytch.OpenApiClient.V1.Webauthn;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The b2b property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.B2bRequestBuilder B2b
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.B2bRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connected_apps property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Connected_apps.Connected_appsRequestBuilder Connected_apps
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Connected_apps.Connected_appsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The crypto_wallets property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Crypto_wallets.Crypto_walletsRequestBuilder Crypto_wallets
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Crypto_wallets.Crypto_walletsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The debug property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Debug.DebugRequestBuilder Debug
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Debug.DebugRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fingerprint property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Fingerprint.FingerprintRequestBuilder Fingerprint
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Fingerprint.FingerprintRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The idp property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Idp.IdpRequestBuilder Idp
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Idp.IdpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The impersonation property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Impersonation.ImpersonationRequestBuilder Impersonation
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Impersonation.ImpersonationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The m2m property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.M2m.M2mRequestBuilder M2m
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.M2m.M2mRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The magic_links property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Magic_links.Magic_linksRequestBuilder Magic_links
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Magic_links.Magic_linksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The otps property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Otps.OtpsRequestBuilder Otps
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Otps.OtpsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The passwords property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder Passwords
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Passwords.PasswordsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rbac property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Rbac.RbacRequestBuilder Rbac
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Rbac.RbacRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rules property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Rules.RulesRequestBuilder Rules
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Rules.RulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sessions property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Sessions.SessionsRequestBuilder Sessions
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Sessions.SessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The totps property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Totps.TotpsRequestBuilder Totps
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Totps.TotpsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verdict_reasons property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Verdict_reasons.Verdict_reasonsRequestBuilder Verdict_reasons
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Verdict_reasons.Verdict_reasonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webauthn property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Webauthn.WebauthnRequestBuilder Webauthn
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Webauthn.WebauthnRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
