// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\sso\saml\{organization_id}\connections\{connection_id}\verification_certificates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Verification_certificatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Stytch.OpenApiClient.v1.b2b.sso.saml.item.connections.item.verification_certificates.item collection</summary>
        /// <param name="position">The ID of the certificate to be deleted.</param>
        /// <returns>A <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Item.WithCertificate_ItemRequestBuilder"/></returns>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Item.WithCertificate_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("certificate_id", position);
                return new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Item.WithCertificate_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Verification_certificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Verification_certificatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/sso/saml/{organization_id}/connections/{connection_id}/verification_certificates", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Sso.Saml.Item.Connections.Item.Verification_certificates.Verification_certificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Verification_certificatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/sso/saml/{organization_id}/connections/{connection_id}/verification_certificates", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
