// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Login_or_create;
using Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Send;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.Otps.Sms
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\otps\sms
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login_or_create property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Login_or_create.Login_or_createRequestBuilder Login_or_create
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Login_or_create.Login_or_createRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Send.SendRequestBuilder Send
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.SmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/otps/sms", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.Otps.Sms.SmsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/otps/sms", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
