// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Organizations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\discovery
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscoveryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The intermediate_sessions property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Intermediate_sessionsRequestBuilder Intermediate_sessions
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Intermediate_sessions.Intermediate_sessionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.DiscoveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoveryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/discovery", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Discovery.DiscoveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DiscoveryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/discovery", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
