// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Authenticate;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Discovery;
using Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Email;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\b2b\magic_links
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Magic_linksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authenticate property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Authenticate.AuthenticateRequestBuilder Authenticate
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Authenticate.AuthenticateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The discovery property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Discovery.DiscoveryRequestBuilder Discovery
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Discovery.DiscoveryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Magic_linksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Magic_linksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/magic_links", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Stytch.OpenApiClient.V1.B2b.Magic_links.Magic_linksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Magic_linksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/b2b/magic_links", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
